fragment ProductFragment on Product {
  id
  masterData {
    current {
      name(locale: $locale)
      description(locale: $locale)
      slug(locale: $locale)
      categories {
        id
        name(locale: $locale)
        slug(locale: $locale)
        ancestors {
          id
          name(locale: $locale)
          slug(locale: $locale)
        }
      }
      allVariants {
        sku
        images {
          url
        }
        price(currency: "EUR") {
          value {
            centAmount
            currencyCode
          }
          discounted {
            value {
              centAmount
              currencyCode
            }
          }
        }
        attributesRaw {
          value
          attributeDefinition {
            name
            label(locale: $locale)
            type {
              name
            }
          }
        }
      }
    }
  }
}
