#import "../../fragments/addresses/AddressFragment.gql"

fragment CustomerFragment on Customer {
  id
  title
  email
  firstName
  lastName
  customerNumber
  addresses {
    ...AddressFragment
  }
  defaultShippingAddress {
    ...AddressFragment
  }
  defaultBillingAddress {
    ...AddressFragment
  }
}
