#import "../../fragments/categories/CategoryFragment.gql"

query GetAllCategories {
  categories(where: "parent is not defined") {
    results {
      ...CategoryFragment
      children {
        ...CategoryFragment
        children {
          ...CategoryFragment
        }
      }
    }
  }
}
