#import "../../fragments/categories/CategoryExtendedFragment.gql"

query GetAllCategories {
  categories(where: "parent is not defined") {
    results {
      ...CategoryExtendedFragment
      children {
        ...CategoryExtendedFragment
        children {
          ...CategoryExtendedFragment
        }
      }
    }
  }
}
